leaf.name=com.sankuai.leaf.opensource.test
leaf.segment.enable=true
leaf.jdbc.url=jdbc:mysql://localhost:3307/leaf?useUnicode=true&characterEncoding=utf-8&useSSL=false
leaf.jdbc.username=REPLACE_WITH_LOCAL_VALUE
leaf.jdbc.password=REPLACE_WITH_LOCAL_VALUE

leaf.snowflake.enable=true
leaf.snowflake.zk.address=127.0.0.1:2181
leaf.snowflake.port=2222
